services:
  postgres:
    image: postgres:16
    container_name: tickflow_postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: tickflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tickflow_redis
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: tickflow_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    environment:
      RI_ACCEPT_TERMS_AND_CONDITIONS: "true"
      RI_APP_PORT: "5540"
      RI_REDIS_HOST: "redis"
      RI_REDIS_PORT: "6379"
      RI_REDIS_ALIAS: "TickFlow Redis"
    depends_on:
      - redis
    volumes:
      - redisinsight:/data

volumes:
  pgdata:
  redisinsight:
